name: Update Seasonal GIF

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine season
        id: season
        run: |
          month=$(date +%m)
          month=3
          if [ "$month" -ge 3 ] && [ "$month" -le 5 ]; then
            echo "SEASON=spring" >> $GITHUB_ENV
          elif [ "$month" -ge 6 ] && [ "$month" -le 8 ]; then
            echo "SEASON=summer" >> $GITHUB_ENV
          elif [ "$month" -ge 9 ] && [ "$month" -le 11 ]; then
            echo "SEASON=autumn" >> $GITHUB_ENV
          else
            echo "SEASON=winter" >> $GITHUB_ENV
          fi

      - name: Debug season
        run: |
          echo "Detected season: $SEASON"
          grep '<img src="autumn.gif' README.md || echo "No image found in README"

      - name: Update README
        id: update
        run: |
          GIF_LINE="<img src=\"${SEASON}.gif\" alt=\"Alt text\" width=\"500\" />"
          CURRENT_LINE=$(grep -o '<img src=".*\.gif" alt="Alt text" width="500" />' README.md || echo "")
      
          echo "Detected season: $SEASON"
          echo "Current line: $CURRENT_LINE"
      
          if [ "$CURRENT_LINE" != "$GIF_LINE" ]; then
            echo "Season changed — updating README..."
            sed -i "s|<img src=\".*\.gif\" alt=\"Alt text\" width=\"500\" />|$GIF_LINE|" README.md
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "No change needed."
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Commit changes if GIF changed
        if: env.CHANGED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update seasonal GIF to $SEASON" || echo "No changes to commit."
          git push || echo "Nothing to push."
